### ISSUE TITLE
Segment at the begining of video can cause video to repeat

### ISSUE THREAD

**Issue by stephen304** [erdnaxeli/castblock#9]
I believe this might be an out of bounds issue where skipping past the end any amount causes it to seek to the beginning. An example is the latest [wendover productions video](https://www.youtube.com/watch?v=4p0fRlCHYyg) (assuming you get the same or similar segments).

I'm not entirely sure whether I did anything for this because I remember thinking about it at one point...

**Comment by erdnaxeli** [comment]
I can reproduce it. If the chromecast send the video total duration this should be easy, else…

**Comment by erdnaxeli** [comment]
Actually the bug was not exactly that. What happens is that this video also has a sponsor segment at the start of the video, and when the video ends (if there is no other next after), the chromecast send a message with the same media, current time being 0, and player_state being "PAUSED". Except that I was not checking the player state, so it just see that 0 is in the first segment and skips it.

Anyway, this is fixed.
